import { atom } from 'recoil'

export const itemsState = atom({
  key: 'items',
  default: {
    door_1: {
      position: [0,0,0],
      rotation: [0,0,0],
      installed: false,
      installing: false,
   },
   roof_1: {
      position: [0,0,0],
      rotation: [0,0,0],
      installed: false,
      installing: false,
   },
      sofa_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
   fridge_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  floor_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  box_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  camera_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  coffee_table_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  flower_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  kitchen_chair_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  microwave_oven_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  training_item_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  training_item_2: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  washing_machine_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  tv_1: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  lamp_2: [
   {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
      {
      position: [0,0,0],
      rotation: [0,0,0],
      scale: [0,0,0],
      installed: false,
      installing: false,
   },
],
  window_1: {
      position: [0,0,0],
      rotation: [0,0,0],
      installed: false,
      installing: false,
   },
    window_2: {
      position: [0,0,0],
      rotation: [0,0,0],
      installed: false,
      installing: false,
   },
    bed_1: [
      {
         position: [0,0,0],
         rotation: [0,0,0],
         installed: false,
         installing: false,
      },
      {
         position: [0,0,0],
         rotation: [0,0,0],
         installed: false,
         installing: false,
      },
      {
         position: [0,0,0],
         rotation: [0,0,0],
         installed: false,
         installing: false,
      },
   ],
  changeIndex: 0
},
dangerouslyAllowMutability: true
})